@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
Content-Type: application/json
x-api-key: secretKey

{
  "make": "Opel",
  "model": "Corsa",
}
###

@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}} HTTP/3.0
content-type: application/json
x-api-key: secretKey


###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###

DELETE  {{endpoint}}/6abcd2ddb56e6b3aed1be4cf HTTP/3.0
content-type: application/json
x-api-key: secretKey
###

PUT  {{endpoint}}/6abcd84d0889f8b529aeef28 HTTP/3.0
content-type: application/json
x-api-key: secretKey

{
  "make": "Opel",
  "model": "Astra",
  "year": 1930
}
###