@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
Content-Type: application/json
x-api-key: secretKey

{
  "make": "Opel",
  "model": "Corsa"
}
###

@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}} HTTP/3.0
content-type: application/json
x-api-key: secretKey


###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ab53f87061829cab246e44c HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json
